### ISSUE TITLE
Enhancement: Support for DNS style S3 Bucket naming

### ISSUE THREAD

**Issue by adnoh** [bitnami/bitnami-docker-minio#11]
The support is implemented upstream https://github.com/minio/minio/issues/4681
But, 'This feature is on only when server is started with --address <fqdn>'
So it should be possible by changing the /opt/bitnami/scripts/minio/run.sh

Amazon is deprecating path-style buckets (https://forums.aws.amazon.com/ann.jspa?annID=6776) so it would be good to have this feature

**Comment by andresbono** [comment]
Thanks for raising this issue to our attention, @adnoh. Did you test the change on your side? Would you like to contribute with the implementation of the change that you are proposing? Contributions are more than welcome!

You can find the Bash scripts here: https://github.com/bitnami/bitnami-docker-minio/tree/master/2020/debian-10/rootfs/opt/bitnami/scripts.

If you are interested, please let us know and we can work with you to implement this new enhancement.

**Comment by adnoh** [comment]
After a lot of digging it seems to work but it's just horrible documented in the upstream ;) all you need to do is set the MINIO_DOMAIN ENV var

If you go for `docker run -e MINIO_DOMAIN=mimi.test -v A:\temp\tmpdata:/data:rw -P --hostname mimi.test --name mimi -e MINIO_ACCESS_KEY=access -e MINIO_DEFAULT_BUCKETS=test:public -e MINIO_SECRET_KEY=secret bitnami/minio` you can access a file foo.jpg in your bucket test via url http://test.mimi.test:<yourport>/foo.jpg

So I guess this can be closed, sorry for the noise. @andresbono  If you have a good place to highlight it in the documentation, I guess it is a nice feature you can enable with just one env var.

**Comment by andresbono** [comment]
Thanks for investigating it and sharing the solution here! Other users will benefit from it.

As this is an environment variable directly used by the minio binaries, we don't usually document it in the readme and we do is pointing to the minio configuration guide: https://docs.min.io/docs/minio-server-configuration-guide.html
