### ISSUE TITLE
Add MINIO_JSON_LOGGING or MINIO_EXTRA_ARGS

### ISSUE THREAD

**Issue by lathspell** [bitnami/bitnami-docker-minio#15]
**Description**

The `run.sh` defines the arguments for `minio server ...` but has no way to add extra arguments. Although Minio has almost none, at least "--json" would be helpful for the typical Kubernetes stdout log scraper. 

**Steps to reproduce the issue:**

1. Try the new "args:" variable from the Bitnami Minio Helm chart as introduced today.
2. Get "/opt/bitnami/scripts/minio/entrypoint.sh: line 22: exec: --: invalid option" 

**Describe the results you received:**

Logging is plaintext

**Describe the results you expected:**

Logging can be configured to JSON

**Comment by juan131** [comment]
Hi @lathspell 

Could you please specify how you're exactly setting the `args` parameter to add you custom flags? You should be using a **values.yaml** such as the one below:

```yaml
args:
  - /opt/bitnami/scripts/minio/run.sh
  - --json
```

That said, you're right and extra args are not appended to the `mino server` command. That can be fixed by applying the change below at https://github.com/bitnami/bitnami-docker-minio/blob/master/2021/debian-10/rootfs/opt/bitnami/scripts/minio/run.sh:

```diff
--- a/2021/debian-10/rootfs/opt/bitnami/scripts/minio/run.sh
+++ b/2021/debian-10/rootfs/opt/bitnami/scripts/minio/run.sh
@@ -30,6 +30,8 @@ if is_boolean_yes "$MINIO_DISTRIBUTED_MODE_ENABLED"; then
 else
     ARGS+=("--address" ":${MINIO_PORT_NUMBER}" "${MINIO_DATADIR}")
 fi
+# Add any extra flags passed to this script
+ARGS+=("$@")

 info "** Starting MinIO **"
 if am_i_root; then
[minio-extra-args 5435bf370f788] MinIO - allow extra arguments to start MinIO server
 1 file changed, 2 insertions(+)
```

We'll release a revision of the MinIO image including this change.

**Comment by lathspell** [comment]
Thanks for the new Docker image release.
Regarding to your first question, I had only used the following. As the exact location of "run.sh" isn't documented in the values.yaml, I did not want to specifiy it. And even if, shouldn't it go to the "command:" parameter? Or is that rather for "entrypoint.sh"?

```
# command: []
args:
  - --json
```

**Comment by juan131** [comment]
Hi @lathspell 

A new revision of the image was released applying the changes I mentioned before, see https://github.com/bitnami/bitnami-docker-minio/commit/cc35a20e813312e580bd004731b5ad6659203512

I'll include this revision by default in the chart on [this PR](https://github.com/bitnami/charts/pull/5750).

--- 

> Regarding to your first question, I had only used the following. As the exact location of "run.sh" isn't documented in the values.yaml, I did not want to specifiy it. And even if, shouldn't it go to the "command:" parameter? Or is that rather for "entrypoint.sh"?

You shouldn't modify the `command` in principle. The `args` overwrites the default container "cmd", therefore you should use the solution I shared before to properly add new flags to `minio server`:

```yaml
args:
  - /opt/bitnami/scripts/minio/run.sh
  - --json
```

**Comment by lathspell** [comment]
Having to guess or lookup the run.sh path ist suboptimal. But even if I write it that way, the Helm chart bitnami/minio 6.3.0 with explicit use of "image.tag: 2021.3.17-debian-10-r1" gives the following error:

```
 17:00:36.81 INFO  ==> ** Starting MinIO **
ERROR Invalid command line arguments: Incorrect number of endpoints provided [http://minio21-{0...3}.minio21-headless.minio-dev.svc.cluster.local/data --json]
      > Please provide an even number of endpoints greater or equal to 4
```

Maybe the URLs and the additional parameter are understood as one command line parameter with a space within?

**Comment by juan131** [comment]
Hi @lathspell 

I was able to reproduce the issue. It was a problem with the position where the custom flags were injected, sorry for that.

This issue is solved in the new image revision **2021.3.17-debian-10-r2**. Could you please give it a try by installing the MinIO chart using this tag?

```console
$ helm install minio bitnami/minio \
    --set image.tag="2021.3.17-debian-10-r2" \
    --set mode="distributed" \
    --set args[0]="/opt/bitnami/scripts/minio/run.sh" \
    --set args[1]="--json"
```

**Comment by lathspell** [comment]
Now it works, thanks!

**Comment by juan131** [comment]
Great! I proceed to close this issue. Feel free to reopen it if you require further help.
