### ISSUE TITLE
Incorrect value of MINIO_HTTP_TRACE in README.md

### ISSUE THREAD

**Issue by halochou** [bitnami/bitnami-docker-minio#18]
https://github.com/bitnami/bitnami-docker-minio/blame/1493dd37970332de604915daaaee9b1cc78f2322/README.md#L369

When `MINIO_HTTP_TRACE` is set as this example, minio cannot start.
This seems to be caused by `entrypoint.sh` which used `-w` to check permission of `MINIO_HTTP_TRACE`.

**Comment by miguelaeh** [comment]
Hi @halochou ,
Could you please share some logs of the failure, please?

**Comment by halochou** [comment]
Sorry, my setup has gone. If you cannot reproduce this issue, feel free to close it.
