### ISSUE TITLE
Versions not being upgraded

### ISSUE THREAD

**Issue by MSuter6** [bitnami/bitnami-docker-minio#20]
It appears that the latest release of this docker image is still pointing to the 2021.6.17 version of minio (https://github.com/bitnami/bitnami-docker-minio/releases). In the meantime, there have been several releases of minio with the most recent one being 2021.8.25 (https://github.com/minio/minio/releases).

Could this potentially be an issue with the automated dependency version update (bitnami-bot)? 
Many thanks in advance for looking into this.

**Comment by beltran-rubo** [comment]
@MSuter6 new MinIO version 021.9.9 was already released in the catalog
