### ISSUE TITLE
Console-address is not supported in distributed mode

### ISSUE THREAD

**Issue by sergeyshaykhullin** [bitnami/bitnami-docker-minio#22]
**Description**

Console address is not set if mode is distributed

**Steps to reproduce the issue:**

1. Use bitnami minio helm chart
2. Deploy with distributed mode

**Describe the results you received:**

Get `WARNING: Console endpoint is listening on a dynamic port (37259), please use --console-address ":PORT" to choose a static port.`

**Describe the results you expected:**
Console address is provided and ui can access from ingress/service

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/bitnami/bitnami-docker-minio/blob/166382bc690b589061a799a739b2ef144ad40ca5/2021/debian-10/rootfs/opt/bitnami/scripts/minio/run.sh#L32

Also now with 8.0.0 minio helm chart any distributed minio deployments are broken, because liveness/readiness probes pointing to console service/port 9001, but it is random

**Comment by marcosbc** [comment]
Hi @sergeyshaykhullin, thanks for reporting this. Do you mean that making `--console-address` a common property for both standalone and distributed modes would solve this issue? If so, would you be open to contributing the fix via a PR?

**Comment by sergeyshaykhullin** [comment]
@marcosbc What should i do to deploy new image version? Does this a daily process and it will happen in an hour?

**Comment by marcosbc** [comment]
Hi @sergeyshaykhullin, usually images are released with a daily processes. However, it seems like our internal CI is throwing some errors that we're looking into, so it may take a bit longer than usual.

In the meantime, you can always `docker build` the image from the repo and use it. If you didn't make any change to it, it's going to be almost identical to what gets published.

**Comment by sergeyshaykhullin** [comment]
Thanks

**Comment by marcosbc** [comment]
No problem! FYI `2021.9.9-debian-10-r5` was just released in our pipeline, with the changes from #24.
