### ISSUE TITLE
Release plan for multi-arch image

### ISSUE THREAD

**Issue by bita-tamada** [bitnami/bitnami-docker-minio#23]
Hi.
I've been using this wonderful docker image with great appreciation, but it doesn't work properly on my M1 Mac.
As you may know, minio has released multi-arch images, is there any plan to release a linux/arm64 compatible image as well?
I'm sorry if this seems like a rude question.

**Comment by carrodher** [comment]
Hi, we created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
