### ISSUE TITLE
share don't find my domain

### ISSUE THREAD

**Issue by fusengine** [bitnami/bitnami-docker-minio#29]
why this not find my domain if I want share file.

         
**http://172.23.0.2:9000**/hhhh/ca_bundle.crt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=LVAAVU1VNE3RVIFU6NZE%2F20210930%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210930T163941Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJMVkFBVlUxVk5FM1JWSUZVNk5aRSIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoiY29uc29sZUFkbWluIn0.9-eIxqlF3oui6bEtdIPfIJs8J4MG3NialmZZgoxJ50cZlLiPwLJ-BV3AdU_yB7_Ce7mjU-ekSgk-TXWhNNpp0A&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=8f8b00b30aca20e3255811ab55ba6338698e318b2403d1b25778508cc3561fa3 

http://172.23.0.2:9000 = i want to replace whit my domain but why is very complicated to deploy this, is very very strange.

**Comment by rafariossaa** [comment]
Hi,
  Not very sure which is the issue here. Those URLs use private IPs.
  Could you explain what you have done and what you want to achive ? Please, indicate parameters used and errors found in the logs.

**Comment by rafariossaa** [comment]
I am closing this issue.
Please don't hesitate to reopen it, or to create a new one if needed.

**Comment by 110ermya** [comment]
how chenge 
local host:9000      
domain  https:test.test.com
 
![image](https://user-images.githubusercontent.com/49756184/162331152-b80af1f2-4747-4297-bf17-0d22cbe18fae.png)

**Comment by javsalgar** [comment]
Hi,

I see that you already created a ticket in https://github.com/bitnami/bitnami-docker-minio/issues/54 let's continue the conversation there

**Comment by 110ermya** [comment]
docker run -d  --name minio \
    --publish 9000:9000 \
    --publish 9001:9001 \
    --env MINIO_ROOT_USER="new-minio-root-user" \
    --env MINIO_ROOT_PASSWORD="new-minio-root-password" \
    --env MINIO_SERVER_HOST="test.test.com" \
    --volume /path/to/minio-persistence:/data \
    bitnami/minio:latest

![image](https://user-images.githubusercontent.com/49756184/162831814-bebda8fb-e662-489f-b61e-6bf7c98024f5.png)




![image](https://user-images.githubusercontent.com/49756184/162831836-ea863fa2-3869-4f8c-b1db-32d448185fd4.png)

**Comment by 110ermya** [comment]
is not domain

**Comment by 110ermya** [comment]
@javsalgar

**Comment by miguelaeh** [comment]
@110ermya give a try to run it without mounting the volume
