### ISSUE TITLE
Crash on run, no logs

### ISSUE THREAD

**Issue by oliverkane** [bitnami/bitnami-docker-minio#3]
On a clean install of Ubuntu, and a brand new instance of docker installed from get.docker.com's script, this image crashes for me on startup.

Not the foggiest as this just started happening within the past 24 hours.  I'll be trying to find an older image which doesn't seem to have this issue.  I have windows 10 host running WSL2 docker which doesn't seem to have the same issue.  This one has me pretty stumped.  I'll post updates as I know more and will be happy to provide any additional info.

```shell
sevenless@eightmore:~$ sudo docker run --name minio bitnami/minio:latest
 16:49:22.23 
 16:49:22.23 Welcome to the Bitnami minio container
 16:49:22.23 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 16:49:22.24 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 16:49:22.24 Send us your feedback at containers@bitnami.com
 16:49:22.24 
 16:49:22.24 INFO  ==> ** Starting MinIO setup **
 16:49:22.25 INFO  ==> Starting MinIO in background...
 16:49:32.26 INFO  ==> Adding local Minio host to 'mc' configuration...
 16:49:32.28 INFO  ==> MinIO is already stopped...
```

```shell
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-40-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 31.28GiB
 Name: eightmore
 ID: B2UM:RIML:WVG5:7O4O:HW5W:OGRI:FJMH:VOYZ:EQGJ:LIUS:S4CX:EGFY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by oliverkane** [comment]
I grabbed an older image and it appears to no longer occur.  I guess I'll start trying images and see when this started.

![image](https://user-images.githubusercontent.com/1761622/76443007-c3857d00-638f-11ea-98a6-f02e8bbe6320.png)

**Comment by oliverkane** [comment]
This image looks like it's the latest that works for me.  Interesting. 
```
bitnami/minio:2020.2.20
```

**Comment by oliverkane** [comment]
So it appears that the most recent image based on chronlogical tagging/releasing that worked for me is ``` bitnami/minio:2020.2.20``` and the first one that breaks is ```bitnami/minio:2020.2.27-debian-10-r0``` 

Time for some lunch, and then I'll see if I can figure out what's the diff between these images.

**Comment by rafariossaa** [comment]
Hi @oliverkane ,
  I am also checking this. 
  Please, don't hesitate to share your findings. I will come back with mine.

**Comment by rafariossaa** [comment]
Hi @oliverkane ,
  This is a weird issue.
  I checked in one machine ubuntu 19.10 + docker 19.03.6 + kernel 5.3.0-40 + bitnami/minio:2020 (and with other images until 2020.2.20) and happens as you reported.
  But, in other machine ubuntu 18.04 + docker 19.03.5 + kernel 4.4.0-148 + bitnami/minio:2020 and it worked.
  You can check the error if you set the following environment variable:
 ```  - BITNAMI_DEBUG=true```

  I will continue digging in the issue.

**Comment by rafariossaa** [comment]
Hi @oliverkane ,
  I found this [thread](https://github.com/golang/go/issues/37436) , it seems to be a bug in the kernel in ubuntu 19.10.

**Comment by oliverkane** [comment]
Got my dayjob to do for the next 8 hours or so, but I think you're correct. I'll investigate this tonight.

**Comment by oliverkane** [comment]
I can confirm this is caused by that particular kernel.  I'm going to close this and work elsewhere for a workaround. This will self-resolve without any effort from this repo. 

Thanks for the image!

**Comment by patrickstump** [comment]
I can confirm this still appears to be happening on 2020.7.2. 
I am using the helm chart to deploy and on the latest image "docker.io/bitnami/minio:2020.7.2-debian-10-r0" and I received the following error:


```
15:39:15.18 
 15:39:15.29 Welcome to the Bitnami minio container
 15:39:15.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 15:39:15.30 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 15:39:15.30 
 15:39:15.30 INFO  ==> ** Starting MinIO setup **
 15:39:15.34 DEBUG ==> Validating settings in MINIO_* env vars..
 15:39:15.51 INFO  ==> Starting MinIO in background...
 15:39:25.53 INFO  ==> Adding local Minio host to 'mc' configuration...
API: SYSTEM()
Time: 15:39:27 UTC 07/02/2020
DeploymentID: 11f9ce85-0293-4295-8d5c-d2a2b5c95e1d
Error: Access Denied.
       requestHeaders={"method":"GET","reqURI":"/minio/admin/v3/info","header":{"Host":["localhost:9000"],"User-Agent":["MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.GOGET"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"]}}
       5: cmd/auth-handler.go:142:cmd.validateAdminSignature()
       4: cmd/auth-handler.go:157:cmd.checkAdminRequestAuthType()
       3: cmd/admin-handlers.go:834:cmd.validateAdminReq()
       2: cmd/admin-handlers.go:1324:cmd.adminAPIHandlers.ServerInfoHandler()
       1: net/http/server.go:2012:http.HandlerFunc.ServeHTTP()
 15:39:27.22 INFO  ==> MinIO is already stopped...
```

When i go back to the old image 2020.2.20... works.  Any thoughts? Should we reopen this?

**Comment by rafariossaa** [comment]
Hi @patrickstump ,
  Could you check if it is related to the kernel issue ?. 

  As yours is related to the chart, I would suggest you to open the issue in the chart repository just in case it is other kind of issue. It would be nice if you link this tread to give more context.

Thanks forehand.

**Comment by pehbehbeh** [comment]
I still get this error when setting `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` via docker-compose. Without these envs it works.

```yml
  minio:
    image: bitnami/minio:latest
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio
    ports:
      - 9000:9000
```

**Comment by pehbehbeh** [comment]
I think it was an error defining the env vars. It should be:

```yml
  minio:
    image: bitnami/minio:latest
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY= minio
    ports:
      - 9000:9000
```

**Comment by rafariossaa** [comment]
Hi,
  I am happy you were able to solve it.
  Thanks for sharing.
  Don't hesitate to open a new issue if you find further problems.

**Comment by ethernoy** [comment]
I also encountered this issue when deploying using bitnami MinIO helm chart. I just raised the issue in bitnami helm chart repository. https://github.com/bitnami/charts/issues/5951

**Comment by carrodher** [comment]
Thanks for letting us know, in order to avoid duplicating efforts let's maintain this issue closed since we are already providing support in the new one

**Comment by Weilbyte** [comment]
Encountering this issue while running `bitnami/minio:latest` in K8S. As envs I have set `MINIO_ACCESS_KEY`/`MINIO_SECRET_KEY`/`MINIO_ROOT_USER` & `MINIO_ROOT_PASSWORD`.

**Comment by powehuda** [comment]
sorry i have Encountering this issue. 
I've tried several ways from the comments on this issue, but still experiencing the same thing, and i tried to change image
bitnami/minio:latest
bitnami/minio:2021.11.24
bitnami/minio:2020.2.20

buts it's still same
![image](https://user-images.githubusercontent.com/5734783/146679418-4ce2ed7b-b7cc-4307-8549-2f6d6a55fd28.png)

here's what I wrote in docker-compose
  minio:
        image: bitnami/minio:2021.11.24
        container_name: lms_minio
        ports:
            - '9000:9000'
        volumes:
            - ./minio_data/:/data
        environment:
            MINIO_ACCESS_KEY: miniouser
            MINIO_SECRET_KEY: minio123456
            MINIO_FORCE_NEW_KEYS: 'yes'
            BITNAMI_DEBUG: 'true'
        networks:
            - service-net
and this my docker-dekstop version on my mac
![image](https://user-images.githubusercontent.com/5734783/146679498-413002cc-3b11-4113-b2b6-b33f99926255.png).

thanks for the answer

**Comment by rafariossaa** [comment]
Hi @powehuda ,
  Do you mind opening a new issue? That way we can help you better.
 Thanks forehand.

**Comment by gphillips3-chwy** [comment]
> For me that was because of ` MINIO_SECRET_KEY` and `MINIO_ACCESS_KEY` length limit (5 and 8 characters respectively) and putting a new longer value resolved the error.

This still silently fails in the latest image.  It would be great to add a log for this.
