### ISSUE TITLE
ARM Image support

### ISSUE THREAD

**Issue by wyq984700527** [bitnami/bitnami-docker-minio#35]
Dear bitnami: 
          the bitnami/mysql、bitnami/redis、bitnami/minio and so on has no arm images now. could you provider arm images in the future, thank you so much.

**Comment by carrodher** [comment]
Hi all, we just created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by wyq984700527** [comment]
> Hi all, we just created this issue [bitnami/charts#7305](https://github.com/bitnami/charts/issues/7305) that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.
> 
> We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

thank you so much. @carrodher
