### ISSUE TITLE
Unable to open video using get_presigned_url() when the object placed inside the folder

### ISSUE THREAD

**Issue by duongsieu** [bitnami/bitnami-docker-minio#42]
**Description**

**Steps to reproduce the issue:**

1. I upload video in serve minio
2. I access url video url/file_name.mp4
3. result: 
![image](https://user-images.githubusercontent.com/33409331/145506357-0c1dfb8a-c5fa-4aca-8665-07d3e43ee475.png)

**Version**

- docker version: 2021.6.14

**Comment by juan131** [comment]
Hi @duongsieu 

This doesn't seem like an issue related with the Bitnami MinIO image but MinIO itself. Could you please open an issue in the upstream project instead? Thanks in advance.

- https://github.com/minio/minio/issues
