### ISSUE TITLE
/data/.root_user: Permission denied

### ISSUE THREAD

**Issue by ehsansh84** [bitnami/bitnami-docker-minio#43]
**Description**

When I try to run docker container an error will be occured: /opt/bitnami/scripts/libminio.sh: line 270: /data/.root_user: Permission denied

**Steps to reproduce the issue:**

docker run --rm --name minio -p 9010:9000  -p 9001:9001 -v /volumes/minio:/data bitnami/minio:2021.12.20-debian-10-r1

**Describe the results you received:**

 08:58:17.89 
 08:58:17.90 Welcome to the Bitnami minio container
 08:58:17.90 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 08:58:17.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 08:58:17.90 
 08:58:17.90 INFO  ==> ** Starting MinIO setup **
/opt/bitnami/scripts/libminio.sh: line 270: /data/.root_user: Permission denied

**Describe the results you expected:**

I expect to run without error!

**Version**
```
Docker version 20.10.12, build e91ed57
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-88-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.774GiB
 Name: minio
 ID: 7VSX:P3B4:3JEU:A4EA:LB5K:5Q3J:BDN4:Q6SW:I5Q7:CYYM:IZXF:MUL4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by juan131** [comment]
Hi @ehsansh84 

As it's explained in the ["Persisting your database" section of the README.md](https://github.com/bitnami/bitnami-docker-minio#persisting-your-database), the mounted files and directories must have the proper permissions for the UID `1001` which is the default container's UID (find more info [here](https://github.com/bitnami/bitnami-docker-minio#why-use-a-non-root-container)). Therefore, you need to ensure that the permissions in your host path `/volumes/minio` are correct.

**Comment by ehsansh84** [comment]
It was my mistake, thanks to @juan131
