### ISSUE TITLE
what is the default user/passwd

### ISSUE THREAD

**Issue by szthanatos** [bitnami/bitnami-docker-minio#44]
👆
if you have changed minio's default setting, why not **make it clear** in your doc.

**Comment by carrodher** [comment]
Default username and password were not changed recently, see https://github.com/bitnami/bitnami-docker-minio/blame/d2b9ab2ed9b85a0295a298150d35a5815407b0d2/2021/debian-10/rootfs/opt/bitnami/scripts/minio-env.sh#L70

By default the creds are
- User: minio
- Pass: miniosecret
