### ISSUE TITLE
unable to execute putObject, accessKeyId does not exist

### ISSUE THREAD

**Issue by crozet-magenta** [bitnami/bitnami-docker-minio#52]
### Name and Version

public.ecr.aws/bitnami/minio:2022.3.5

### What steps will reproduce the bug?

using this config in the docker image, when I try to upload a file into the bucket

```yml
attachments_datastore:
    image: public.ecr.aws/bitnami/minio:2022.3.5
    environment:
      - MINIO_ACCESS_KEY=xxxx
      - MINIO_SECRET_KEY=xxxx
      - TZ=:/etc/localtime
      - MINIO_DEFAULT_BUCKETS=bridge-test-fr
    networks:
      egress: ~
      datastore:
        aliases:
          - minio.datastore.loctest
```

### What is the expected behavior?

The code of the app has not been changed and it works fine with previous version `public.ecr.aws/bitnami/minio:2022.3.3`

### What do you see instead?

```
Error executing "PutObject" on "http://minio.datastore.loctest:9000/bridge-test-fr/xxx"; AWS HTTP error: Client error: `PUT http://minio.datastore.loctest:9000/bridge-test-fr/xxx` resulted in a `403 Forbidden` response:
      <?xml version="1.0" encoding="UTF-8"?>
      <Error><Code>InvalidAccessKeyId</Code><Message>The Access Key Id you provided doe (truncated...)
       InvalidAccessKeyId (client): The Access Key Id you provided does not exist in our records. - <?xml version="1.0" encoding="UTF-8"?>
      <Error><Code>InvalidAccessKeyId</Code><Message>The Access Key Id you provided does not exist in our records.</Message><Key>xxx</Key><BucketName>bridge-test-fr</BucketName><Resource>/bridge-test-fr/xxx</Resource><RequestId>16DA751BA1B57DA9</RequestId><HostId>5ebbb734-31fb-4844-ba08-b3408a47aff6</HostId></Error> (Aws\S3\Exception\S3Exception)
```

### Additional information

I also tried to change the access/secret key with this name with no luck, the error is the same : 
```
- MINIO_SERVER_ACCESS_KEY=xxxx
- MINIO_SERVER_SECRET_KEY=xxxx
```

**Comment by juan131** [comment]
Hi @crozet-magenta 

I have some questions:

- Did your access/secret key changed? 
- Are you mounting any volume in your containers to persist the data?
- Are you including special characters in your access/secret key?

**Comment by crozet-magenta** [comment]
Hi Juan thank you for your reply.

my access/secret key did not change recently
no volume is mounted as it is just a container used for testing on the CI so the persistence is not required.
the access key uses upper case letters and numbers only and the access key is using alphanumeric and `/`

**Comment by AndrGab** [comment]
Hi Juan,
I'm with the same issue here.
`<Error><Code>InvalidAccessKeyId</Code><Message>The Access Key Id you provided does not exist in our records.</Message><Key>`

5 days ago it worked fine and I didn't change my code.

Thanks

**Comment by miguelaeh** [comment]
Hi guys, looks like the latest version is `2022.3.14`, could you give it a try?

**Comment by crozet-magenta** [comment]
Hi,
I made a quick test and it seems to be ok, i'll do some more tests this evening to confirm everything is fine

**Comment by AndrGab** [comment]
I tried today and still got the same error here

**Comment by miguelaeh** [comment]
Hi guys, sorry for the delayed response. I have found [this](https://github.com/bitnami/bitnami-docker-minio/commit/70cab150826be250f29ee197c5a9b8cd5a198b95) commit that looks to be related to the issue.
Does it work with the latest version if you use  `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` ?

**Comment by crozet-magenta** [comment]
It works fine with those env vars on the latest version, thank you for your help 🙂

**Comment by miguelaeh** [comment]
Thanks for checking!

**Comment by AndrGab** [comment]
thank you @miguelaeh 👍🏽
