### ISSUE TITLE
Trying to start minio container with certificates and container after 4-6 seconds stops

### ISSUE THREAD

**Issue by virgisd** [bitnami/bitnami-docker-minio#53]
### Name and Version

 bitnami/minio:latest

### What steps will reproduce the bug?

1. docker run --name minio --publish 9000:9000 --publish 9001:9001 --mount 'type=bind,src=/mnt/storage/,dst=/data' --mount 'type=bind,src=/mnt/certs/,dst=/certs' --env MINIO_ROOT_USER="user" --env MINIO_ROOT_PASSWORD="password" bitnami/minio:latest
2. content for /mnt/cert is public.crt and private.key issued by Let's Encrypt

### What is the expected behavior?

running container

### What do you see instead?

08:34:22.56 Welcome to the Bitnami minio container
 08:34:22.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 08:34:22.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 08:34:22.57
 08:34:22.57 INFO  ==> ** Starting MinIO setup **
minio 08:34:22.59 INFO  ==> Starting MinIO in background...
minio 08:34:32.64 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 08:34:32.74 INFO  ==> MinIO is already stopped...

### Additional information

if i remove --mount 'type=bind,src=/mnt/certs/,dst=/certs' then creating container eveything is working.
public.crt is content with fullchain.pem

**Comment by virgisd** [comment]
Hi,

with --env MINIO_SKIP_CLIENT=yes application started.

**Comment by virgisd** [comment]
Also if trying to login got error:
Post "https://172.17.0.5:9000/": x509: cannot validate certificate for 172.17.0.5 because it doesn't contain any IP SANs

**Comment by fmulero** [comment]
I reproduced exactly the same issue, it seems there is a misconfiguration about TLS

**Comment by virgisd** [comment]
Hi,
now then starting container got error:
cp: cannot stat '/certs/CAs/public.crt': No such file or directory

 certificate and private key are in mounted catalog /certs/ like it was documented in minio documentation.
Do i need move public.crt to this new folder?

**Comment by fmulero** [comment]
Yes, you right. At the moment we need to copy the `public.crt` file to `CAs` folder. It will be fixed in next version

**Comment by virgisd** [comment]
Not working. No errors after about 6-8 seconds containers shutdown:
 17:49:46.74
 17:49:46.74 Welcome to the Bitnami minio container
 17:49:46.74 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:49:46.74 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:49:46.75
 17:49:46.75 INFO  ==> ** Starting MinIO setup **
minio 17:49:46.77 INFO  ==> Starting MinIO in background...
minio 17:49:56.85 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 17:49:56.99 INFO  ==> MinIO is already stopped...

**Comment by fmulero** [comment]
This is the content of my certs directory

```shell
.
|____CAs
| |____public.crt
|____private.key
|____public.crt
```
And I am running the the docker image with this command:
```bash
docker run --name minio --rm --publish 9000:9000 --publish 9001:9001 --mount "type=bind,src=$(pwd)/storage/,dst=/data" --mount "type=bind,src=$(pwd)/certs/,dst=/certs" --env MINIO_ROOT_USER="user" --env MINIO_ROOT_PASSWORD="password" --env BITNAMI_DEBUG=true --env MINIO_SCHEME=https bitnami/minio:2022.3.24-debian-10-r1
```

Al the problems are introduced by the client. You can skip the client installation with `--env MINIO_SKIP_CLIENT=yes`

**Comment by fmulero** [comment]
Probably you need to set `MINIO_SERVER_URL`. Please have a look to [MinIO documentation](https://docs.min.io/docs/minio-quickstart-guide.html#:~:text=Test%20MinIO%20Connectivity) (Test MinIO Connectivity section)

**Comment by virgisd** [comment]
Now everything ok.
