### ISSUE TITLE
how env domain share file minio

### ISSUE THREAD

**Issue by 110ermya** [bitnami/bitnami-docker-minio#54]
### Name and Version

bitnami/minio

### What steps will reproduce the bug?

how env domain share file minio

### What is the expected behavior?

how env domain share file minio

### What do you see instead?

how env domain share file minio???

### Additional information

how env domain share file minio

**Comment by 110ermya** [comment]
how chenge
local host:9000
domain https:test.test.com


![image](https://user-images.githubusercontent.com/49756184/162331332-be52926d-cb9e-41df-857b-c578562547dd.png)

**Comment by javsalgar** [comment]
Hi,

Did you check the `MINIO_SERVER_HOST` environment variable?
