### ISSUE TITLE
Minio7.1.1

### ISSUE THREAD

**Issue by amitrasap** [bitnami/bitnami-docker-minio#58]
### Name and Version

 minio-7.1.1.tgz

### What steps will reproduce the bug?

Deploying Minio using Rancher 

### What is the expected behavior?

Minio Deployment

### What do you see instead?
```
Events:
  Type     Reason              Age                   From                     Message
  ----     ------              ----                  ----                     -------
  Normal   Scheduled           4m38s                 default-scheduler        Successfully assigned minio/minio-6b7486dc74-hkn5n to ls6819
  Warning  FailedAttachVolume  23s (x10 over 4m38s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-c3c0bf29-291a-4efe-a9ac-289b93e1af74" : rpc error: code = Aborted desc = volume pvc-c3c0bf29-291a-4efe-a9ac-289b93e1af74 is not ready for workloads
  Warning  FailedMount         19s (x2 over 2m35s)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-5b7lj]: timed out waiting for the condition
```
### Additional information

Hi Team,

Need some help in deploying my minio image .

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami MinIO Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
