### ISSUE TITLE
cannot change password using MINIO_SECRET_KEY env var

### ISSUE THREAD

**Issue by mirekphd** [bitnami/bitnami-docker-minio#6]
I set one-time random-generated passwords for all of my containers I develop for our data scientists. 

In case of `bitnami/minio:2020.5.1` I set the password via the MINIO_SECRET_KEY env var (and login via MINIO_ACCESS_KEY). It all works fine during the first run of the container. But once the deployment config is deleted (with its old secrets) and the container is re-started with a new password, the app starts crashing in a loop. The logs are not particularly informative. But the reason for the bug is that randomly generated password preserved from the first run has been hard-coded somewhere inside `~/.minio.sys` (removing this folder corrects the issue - but only for one run). 

I suppose as a workaround I could switch from one-time random passwords to Secrets (I'm using Openshift), to persist the password, but those are arguably less secure, as the users would not change them for years (not to mention the occasional password change that would require my intervention and the removal of all minio data from its hidden settings folder.

**Comment by mirekphd** [comment]
This is the log from the first (correct) run:
```
 19:32:56.03
 19:32:56.04 Welcome to the Bitnami minio container
 19:32:56.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 19:32:56.05 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 19:32:56.06
 19:32:56.06 INFO  ==> ** Starting MinIO setup **
 19:32:56.11 INFO  ==> Starting MinIO in background...
 19:33:06.13 INFO  ==> Adding local Minio host to 'mc' configuration...
 19:33:06.20 INFO  ==> Stopping MinIO...
 19:33:11.24 INFO  ==> ** MinIO setup finished! **

 19:33:11.27 INFO  ==> ** Starting MinIO **
Endpoint:  http://10.131.3.196:9000  http://127.0.0.1:9000

Browser Access:
   http://10.131.3.196:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

Using project "ml-models-tst" on server "https://ocp.warta.pl:8443".
```

Compared to the subsequent (incorrect) runs (with different values of MINIO_SECRET_KEY):
```
 19:35:37.88
 19:35:37.89 Welcome to the Bitnami minio container
 19:35:37.89 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 19:35:37.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 19:35:37.91
 19:35:37.91 INFO  ==> ** Starting MinIO setup **
 19:35:37.96 INFO  ==> Starting MinIO in background...
 19:35:47.97 INFO  ==> Adding local Minio host to 'mc' configuration...
 19:35:48.00 INFO  ==> MinIO is already stopped...
```

**Comment by juan131** [comment]
Hi @mirekphd 

When you don't provide any value for `accessKey.password` or `secretKey.password` when installing or upgrading the chart, those values are randomly generated in the secret.

It's very important to indicate these values both when installing and upgrading the charts, so they're not auto-generated. The problem comes when a value is generated the 1st time the chart is installed, an a different one is generated when upgrading it. When this happen, the persisted data uses a different password and, therefore, MinIO can't start.

A good way to prevent this is to set `accessKey.forcePassword` and `secretKey.forcePassword` to `true`. This way, you'll be forced to set these credentials and they won't be autogenerated. More info at https://github.com/bitnami/charts/blob/master/bitnami/minio/values.yaml#L146

Could you please open an issue at https://github.com/bitnami/charts/issues suggesting us to include an "Upgrade" section in the chart [README.md](https://github.com/bitnami/charts/blob/master/bitnami/minio/README.md) similar to the one we have in other charts (e.g. [PostgreSQL](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md#upgrade))? This should be documented.

**Comment by mirekphd** [comment]
Hi @juan131,

I'm sure you are right in case of unset passwords, but the problem here is different: I do set the password... to a random value (and probably the word "random" created the confusion - in 99% of cases random passwords occur due to a user failure to set any password (static or random):). 

So I do set the password (albeit to randomly generated values, different at each container run - which I generate myself using Openshift generator (`generate: expression`) and pass onto the environmental variable `MINIO_SECRET_KEY` that set the `accessKey.password` property in MinIO). So the passwords are set, I can log in and log out multiple times using them (and have been doing it in less a secure bitnami/minio container for some time). 

The problem occurs when I try to *change* the password (using the same method I set them initially - via the environment variable `MINIO_SECRET_KEY`). Then the container crashes begin. The only solution then is to either remove the hidden settings folder ~(`/.minio.sys`) or to reuse the original password (which is quite hard in my case, because I try to make passwords as variable as possible: different each time and hard to remember - think of online banking website access tokens sent via a text message - this is the ideal of how they should work). Inability to change the password programmatically (via an environment variable populated at random by Openshift and passed to the container) makes this implementation of MinIO container rather insecure IMO, don't you agree?

So the desired action which is currently broken would be the ability to ***change*** password via the the environment variable `MINIO_SECRET_KEY` passed to the container (populated with any value, static or randomly generated by the user).

**Comment by juan131** [comment]
Hi @mirekphd 

> The problem occurs when I try to change the password (using the same method I set them initially - via the environment variable MINIO_SECRET_KEY). 
> ...
> Inability to change the password programmatically (via an environment variable populated at random by Openshift and passed to the container) makes this implementation of MinIO container rather insecure IMO, don't you agree?

This container is designed to configure the access and secret keys during the 1st initialization, reusing existing credentials on following restarts of the containers.

I understand your concerns, but I think that we should **explicitly indicate that we want the passwords to be re-configured** to modify the existing credentials on container restarts.

I can think on implementing the logic to reconfigure them whenever an environment variable (e.g. `MINIO_FORCE_NEW_KEYS`) is set to `yes`. What do you think about this approach? Would that work for yoU? 

Then we can add a parameter in the Helm chart that helps setting this environment variable to yes/no easily.

**Comment by mirekphd** [comment]
> I can think on implementing the logic to reconfigure them whenever an environment variable (e.g. `MINIO_FORCE_NEW_KEYS`) is set to `yes`. What do you think about this approach? Would that work for you?

Sounds perfect! In Kubernetes/Openshift one could set the new variable to "yes" permanently in deployment config / template and then use the standard logic of one-time passwords auto-generated at each creation of new deployment. 

For backward compatibility it would be prudent to set it to "no" by default to conform to the currently supported passwords behavior (regardless of its security impact - after all, users of `MINIO_FORCE_NEW_KEYS=no` containers will be still able to change their passwords from the web interface).

**Comment by juan131** [comment]
@mirekphd I created a couple of PR to address this

**Comment by juan131** [comment]
Hi @mirekphd 

We just released a new version of the MinIO container (`2020.5.8-debian-10-r5`) and the MinIO chart (`3.4.0`) including the changes that allow you to configure MinIO to regenerate the admin credentials every time they're modified in the associated secret.

Here you can find some commands you can try to give this new version a try:

- Install the chart:

```console
$ helm repo update 
$ helm search repo bitnami/minio -l
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/minio	3.4.0        	2020.5.8   	MinIO is an object storage server, compatible w...
bitnami/minio	3.3.10       	2020.5.8   	MinIO is an object storage server, compatible w...
(...)
$ helm install minio bitnami/minio
(...)
```

- Obtain the access and secret key (randomly created) and access using a client:

```console
$ export MINIO_ACCESS_KEY=$(kubectl get secret --namespace default minio -o jsonpath="{.data.access-key}" | base64 --decode)
$ export MINIO_SECRET_KEY=$(kubectl get secret --namespace default minio -o jsonpath="{.data.secret-key}" | base64 --decode)
$ echo "$MINIO_ACCESS_KEY $MINIO_SECRET_KEY"
ZPSD05EH5o T4Cq80Quw3A8OV6F4toS4kuiG6P31qTctZYE54La
$ kubectl run --namespace default minio-client \
     --rm --tty -i --restart='Never' \
     --env MINIO_SERVER_ACCESS_KEY=$MINIO_ACCESS_KEY \
     --env MINIO_SERVER_SECRET_KEY=$MINIO_SECRET_KEY \
     --env MINIO_SERVER_HOST=minio \
     --image docker.io/bitnami/minio-client:2020.5.6-debian-10-r1 -- admin info minio
(...)

●  minio:9000
   Uptime: 54 seconds
   Version: <development>
   Network: 1/1 OK
```

- Perform a chart upgrade (to latest version) forcing new keys, obtain the new access and secret key, and access MinIO:

```console
$ helm upgrade minio bitnami/minio --set forceNewKeys=true
(...)
$ export MINIO_ACCESS_KEY=$(kubectl get secret --namespace default minio -o jsonpath="{.data.access-key}" | base64 --decode)
$ export MINIO_SECRET_KEY=$(kubectl get secret --namespace default minio -o jsonpath="{.data.secret-key}" | base64 --decode)
$ echo "$MINIO_ACCESS_KEY $MINIO_SECRET_KEY"
kuXOSY4VAj 0rj2WvpDV8mE50VxZNFZjXiDizzK6e3cT1DiCMsO
$ kubectl run --namespace default minio-client \
     --rm --tty -i --restart='Never' \
     --env MINIO_SERVER_ACCESS_KEY=$MINIO_ACCESS_KEY \
     --env MINIO_SERVER_SECRET_KEY=$MINIO_SECRET_KEY \
     --env MINIO_SERVER_HOST=minio \
     --image docker.io/bitnami/minio-client:2020.5.6-debian-10-r1 -- admin info minio
(...)

●  minio:9000
   Uptime: 25 seconds
   Version: <development>
   Network: 1/1 OK

(...)
```

**Comment by mirekphd** [comment]
Excellent work @juan131, thank you! We have Openshift (no helm then), but I think these changes will work fine (given that I use the YAML equivalent of `kubectl (oc) --env` to set these variables. I will try out the new `bitnami/minio` build as soon as I find time:)

**Comment by juan131** [comment]
Thanks @mirekphd ! Please do not hesitate to share your feedback once you find time to test it.

**Comment by mirekphd** [comment]
So first the regression test - changing container tag to `2020.5.8-debian-10-r5` replicates the problem reported above - cannot change password using env var `MINIO_SECRET_KEY` (which is correct, given that this behavior of unchangeable keys was preserved as default).

Then we remove the `~/.minio.sys` folder (the only quick workaround known to me to recover from this problem) and change the deployment config section of our template to set the new env var `MINIO_FORCE_NEW_KEYS` to "yes". Upon second container start with a different value of `MINIO_SECRET_KEY`, the keys are reconfigured and then the container restart is forced, which Openshift handles correctly. After the restart, we can log onto the web interface in with the new password that was set by our template.

```
$ oc logs [..]
 18:17:50.20
 18:17:50.20 Welcome to the Bitnami minio container
 18:17:50.20 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 18:17:50.20 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 18:17:50.21
 18:17:50.21 INFO  ==> ** Starting MinIO setup **
 18:17:50.24 INFO  ==> Reconfiguring MinIO credentials...
 18:17:50.24 INFO  ==> Starting MinIO in background...
 18:18:00.25 INFO  ==> Forcing container restart after key regeneration

<the original pod is no longer there, so we need to query the logs of the second pod>
$ oc logs [..]
 18:18:15.34
 18:18:15.34 Welcome to the Bitnami minio container
 18:18:15.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 18:18:15.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 18:18:15.35
 18:18:15.35 INFO  ==> ** Starting MinIO setup **
 18:18:15.38 INFO  ==> Starting MinIO in background...
 18:18:25.39 INFO  ==> Adding local Minio host to 'mc' configuration...
 18:18:25.48 INFO  ==> Stopping MinIO...
 18:18:30.51 INFO  ==> ** MinIO setup finished! **

 18:18:30.53 INFO  ==> ** Starting MinIO **
Endpoint:  http://10.131.2.185:9000  http://127.0.0.1:9000

Browser Access:
   http://10.131.2.185:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```



So the issue has indeed been resolved - minIO keys can now be changed at each container start. Thank you!

**Comment by juan131** [comment]
Great @mirekphd !! I am very glad the solution we implemented works for you too!
