### ISSUE TITLE
/opt/bitnami/scripts/libminio.sh: line 324: /data/.root_user: Permission denied

### ISSUE THREAD

**Issue by turboic** [bitnami/bitnami-docker-minio#66]
### Name and Version

/opt/bitnami/scripts/libminio.sh: line 324: /data/.root_user: Permission denied

### What steps will reproduce the bug?

/opt/bitnami/scripts/libminio.sh: line 324: /data/.root_user: Permission denied

### What is the expected behavior?

/opt/bitnami/scripts/libminio.sh: line 324: /data/.root_user: Permission denied

### What do you see instead?

/opt/bitnami/scripts/libminio.sh: line 324: /data/.root_user: Permission denied

### Additional information

/opt/bitnami/scripts/libminio.sh: line 324: /data/.root_user: Permission denied

**Comment by carrodher** [comment]
Could you please more info about the issue you're facing? It would be nice if you fill the issue template that appears when creating a new issue

**Comment by lmmarisej** [comment]
⚡ root@localhost  /mnt/hgfs/vmvare_shared/docker/minio  d logs minio         
 17:03:58.00 
 17:03:58.00 Welcome to the Bitnami minio container
 17:03:58.00 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:03:58.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:03:58.00 
 17:03:58.01 INFO  ==> ** Starting MinIO setup **
minio 17:03:58.02 INFO  ==> Starting MinIO in background...
minio 17:04:03.04 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3228648035: permission denied.
minio 17:04:03.08 INFO  ==> MinIO is already stopped...
 17:04:03.40 
 17:04:03.41 Welcome to the Bitnami minio container
 17:04:03.41 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:03.41 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:03.41 
 17:04:03.41 INFO  ==> ** Starting MinIO setup **
minio 17:04:03.43 INFO  ==> Starting MinIO in background...
minio 17:04:08.44 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.982068644: permission denied.
minio 17:04:08.48 INFO  ==> MinIO is already stopped...
 17:04:08.93 
 17:04:08.93 Welcome to the Bitnami minio container
 17:04:08.93 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:08.93 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:08.93 
 17:04:08.94 INFO  ==> ** Starting MinIO setup **
minio 17:04:08.95 INFO  ==> Starting MinIO in background...
minio 17:04:13.97 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.2508281896: permission denied.
minio 17:04:14.01 INFO  ==> MinIO is already stopped...
 17:04:14.65 
 17:04:14.65 Welcome to the Bitnami minio container
 17:04:14.65 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:14.65 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:14.65 
 17:04:14.65 INFO  ==> ** Starting MinIO setup **
minio 17:04:14.67 INFO  ==> Starting MinIO in background...
minio 17:04:25.38 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3458339010: permission denied.
minio 17:04:25.42 INFO  ==> MinIO is already stopped...
 17:04:25.78 
 17:04:25.78 Welcome to the Bitnami minio container
 17:04:25.78 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:25.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:25.78 
 17:04:25.79 INFO  ==> ** Starting MinIO setup **
minio 17:04:25.80 INFO  ==> Starting MinIO in background...
minio 17:04:30.82 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.1929799667: permission denied.
minio 17:04:30.88 INFO  ==> MinIO is already stopped...
 17:04:31.33 
 17:04:31.33 Welcome to the Bitnami minio container
 17:04:31.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:31.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:31.34 
 17:04:31.34 INFO  ==> ** Starting MinIO setup **
minio 17:04:31.35 INFO  ==> Starting MinIO in background...
minio 17:04:36.37 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3407770786: permission denied.
minio 17:04:36.42 INFO  ==> MinIO is already stopped...
 17:04:37.07 
 17:04:37.07 Welcome to the Bitnami minio container
 17:04:37.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:37.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:37.07 
 17:04:37.07 INFO  ==> ** Starting MinIO setup **
minio 17:04:37.09 INFO  ==> Starting MinIO in background...
minio 17:04:42.10 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3395709268: permission denied.
minio 17:04:42.17 INFO  ==> MinIO is already stopped...
 17:04:43.22 
 17:04:43.22 Welcome to the Bitnami minio container
 17:04:43.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:43.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:43.23 
 17:04:43.23 INFO  ==> ** Starting MinIO setup **
minio 17:04:43.25 INFO  ==> Starting MinIO in background...
minio 17:04:48.26 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.2287971315: permission denied.
minio 17:04:48.30 INFO  ==> MinIO is already stopped...
 17:04:50.16 
 17:04:50.16 Welcome to the Bitnami minio container
 17:04:50.16 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:50.16 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:50.16 
 17:04:50.16 INFO  ==> ** Starting MinIO setup **
minio 17:04:50.18 INFO  ==> Starting MinIO in background...
minio 17:04:55.20 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.6284733: permission denied.
minio 17:04:55.26 INFO  ==> MinIO is already stopped...
 17:04:58.86 
 17:04:58.86 Welcome to the Bitnami minio container
 17:04:58.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:58.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:58.86 
 17:04:58.87 INFO  ==> ** Starting MinIO setup **
minio 17:04:58.88 INFO  ==> Starting MinIO in background...
minio 17:05:03.91 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3557292193: permission denied.
minio 17:05:03.98 INFO  ==> MinIO is already stopped...
 17:05:10.75 
 17:05:10.75 Welcome to the Bitnami minio container
 17:05:10.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:05:10.75 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:05:10.75 
 17:05:10.75 INFO  ==> ** Starting MinIO setup **
minio 17:05:10.77 INFO  ==> Starting MinIO in background...
minio 17:05:15.79 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.4151566484: permission denied.
minio 17:05:15.85 INFO  ==> MinIO is already stopped...
 17:05:29.03 
 17:05:29.03 Welcome to the Bitnami minio container
 17:05:29.03 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:05:29.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:05:29.03 
 17:05:29.03 INFO  ==> ** Starting MinIO setup **
minio 17:05:29.05 INFO  ==> Starting MinIO in background...
minio 17:05:34.07 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.2762578757: permission denied.
minio 17:05:34.13 INFO  ==> MinIO is already stopped...
 17:05:59.97 
 17:05:59.97 Welcome to the Bitnami minio container
 17:05:59.97 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:05:59.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:05:59.98 
 17:05:59.98 INFO  ==> ** Starting MinIO setup **
minio 17:06:00.00 INFO  ==> Starting MinIO in background...
 ⚡ root@localhost  /mnt/hgfs/vmvare_shared/docker/minio  d logs minio
 17:03:58.00 
 17:03:58.00 Welcome to the Bitnami minio container
 17:03:58.00 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:03:58.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:03:58.00 
 17:03:58.01 INFO  ==> ** Starting MinIO setup **
minio 17:03:58.02 INFO  ==> Starting MinIO in background...
minio 17:04:03.04 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3228648035: permission denied.
minio 17:04:03.08 INFO  ==> MinIO is already stopped...
 17:04:03.40 
 17:04:03.41 Welcome to the Bitnami minio container
 17:04:03.41 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:03.41 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:03.41 
 17:04:03.41 INFO  ==> ** Starting MinIO setup **
minio 17:04:03.43 INFO  ==> Starting MinIO in background...
minio 17:04:08.44 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.982068644: permission denied.
minio 17:04:08.48 INFO  ==> MinIO is already stopped...
 17:04:08.93 
 17:04:08.93 Welcome to the Bitnami minio container
 17:04:08.93 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:08.93 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:08.93 
 17:04:08.94 INFO  ==> ** Starting MinIO setup **
minio 17:04:08.95 INFO  ==> Starting MinIO in background...
minio 17:04:13.97 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.2508281896: permission denied.
minio 17:04:14.01 INFO  ==> MinIO is already stopped...
 17:04:14.65 
 17:04:14.65 Welcome to the Bitnami minio container
 17:04:14.65 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:14.65 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:14.65 
 17:04:14.65 INFO  ==> ** Starting MinIO setup **
minio 17:04:14.67 INFO  ==> Starting MinIO in background...
minio 17:04:25.38 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3458339010: permission denied.
minio 17:04:25.42 INFO  ==> MinIO is already stopped...
 17:04:25.78 
 17:04:25.78 Welcome to the Bitnami minio container
 17:04:25.78 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:25.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:25.78 
 17:04:25.79 INFO  ==> ** Starting MinIO setup **
minio 17:04:25.80 INFO  ==> Starting MinIO in background...
minio 17:04:30.82 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.1929799667: permission denied.
minio 17:04:30.88 INFO  ==> MinIO is already stopped...
 17:04:31.33 
 17:04:31.33 Welcome to the Bitnami minio container
 17:04:31.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:31.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:31.34 
 17:04:31.34 INFO  ==> ** Starting MinIO setup **
minio 17:04:31.35 INFO  ==> Starting MinIO in background...
minio 17:04:36.37 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3407770786: permission denied.
minio 17:04:36.42 INFO  ==> MinIO is already stopped...
 17:04:37.07 
 17:04:37.07 Welcome to the Bitnami minio container
 17:04:37.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:37.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:37.07 
 17:04:37.07 INFO  ==> ** Starting MinIO setup **
minio 17:04:37.09 INFO  ==> Starting MinIO in background...
minio 17:04:42.10 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3395709268: permission denied.
minio 17:04:42.17 INFO  ==> MinIO is already stopped...
 17:04:43.22 
 17:04:43.22 Welcome to the Bitnami minio container
 17:04:43.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:43.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:43.23 
 17:04:43.23 INFO  ==> ** Starting MinIO setup **
minio 17:04:43.25 INFO  ==> Starting MinIO in background...
minio 17:04:48.26 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.2287971315: permission denied.
minio 17:04:48.30 INFO  ==> MinIO is already stopped...
 17:04:50.16 
 17:04:50.16 Welcome to the Bitnami minio container
 17:04:50.16 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:50.16 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:50.16 
 17:04:50.16 INFO  ==> ** Starting MinIO setup **
minio 17:04:50.18 INFO  ==> Starting MinIO in background...
minio 17:04:55.20 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.6284733: permission denied.
minio 17:04:55.26 INFO  ==> MinIO is already stopped...
 17:04:58.86 
 17:04:58.86 Welcome to the Bitnami minio container
 17:04:58.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:04:58.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:04:58.86 
 17:04:58.87 INFO  ==> ** Starting MinIO setup **
minio 17:04:58.88 INFO  ==> Starting MinIO in background...
minio 17:05:03.91 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3557292193: permission denied.
minio 17:05:03.98 INFO  ==> MinIO is already stopped...
 17:05:10.75 
 17:05:10.75 Welcome to the Bitnami minio container
 17:05:10.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:05:10.75 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:05:10.75 
 17:05:10.75 INFO  ==> ** Starting MinIO setup **
minio 17:05:10.77 INFO  ==> Starting MinIO in background...
minio 17:05:15.79 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.4151566484: permission denied.
minio 17:05:15.85 INFO  ==> MinIO is already stopped...
 17:05:29.03 
 17:05:29.03 Welcome to the Bitnami minio container
 17:05:29.03 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:05:29.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:05:29.03 
 17:05:29.03 INFO  ==> ** Starting MinIO setup **
minio 17:05:29.05 INFO  ==> Starting MinIO in background...
minio 17:05:34.07 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.2762578757: permission denied.
minio 17:05:34.13 INFO  ==> MinIO is already stopped...
 17:05:59.97 
 17:05:59.97 Welcome to the Bitnami minio container
 17:05:59.97 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:05:59.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:05:59.98 
 17:05:59.98 INFO  ==> ** Starting MinIO setup **
minio 17:06:00.00 INFO  ==> Starting MinIO in background...
minio 17:06:05.02 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3185281210: permission denied.
minio 17:06:05.06 INFO  ==> MinIO is already stopped...
 17:07:01.72 
 17:07:01.72 Welcome to the Bitnami minio container
 17:07:01.72 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:07:01.73 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:07:01.73 
 17:07:01.73 INFO  ==> ** Starting MinIO setup **
minio 17:07:01.74 INFO  ==> Starting MinIO in background...
minio 17:07:06.76 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.2915110119: permission denied.
minio 17:07:06.81 INFO  ==> MinIO is already stopped...
 17:08:11.90 
 17:08:11.91 Welcome to the Bitnami minio container
 17:08:11.91 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:08:11.91 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:08:11.91 
 17:08:11.91 INFO  ==> ** Starting MinIO setup **
minio 17:08:11.93 INFO  ==> Starting MinIO in background...
minio 17:08:16.94 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3095364666: permission denied.
minio 17:08:16.98 INFO  ==> MinIO is already stopped...
 17:09:21.58 
 17:09:21.58 Welcome to the Bitnami minio container
 17:09:21.58 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:09:21.59 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:09:21.59 
 17:09:21.59 INFO  ==> ** Starting MinIO setup **
minio 17:09:21.62 INFO  ==> Starting MinIO in background...
minio 17:09:26.64 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.585896674: permission denied.
minio 17:09:26.69 INFO  ==> MinIO is already stopped...
 17:10:31.21 
 17:10:31.21 Welcome to the Bitnami minio container
 17:10:31.21 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 17:10:31.21 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 17:10:31.21 
 17:10:31.21 INFO  ==> ** Starting MinIO setup **
minio 17:10:31.23 INFO  ==> Starting MinIO in background...
minio 17:10:36.25 INFO  ==> Adding local Minio host to 'mc' configuration...
mc: <ERROR> Unable to save new mc config. open /.mc/$tmpfile.config.json.3443774643: permission denied.

**Comment by javsalgar** [comment]
Could you add more details about the deployment? How did you deploy minio?

**Comment by fmulero** [comment]
We are moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still facing this issue, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
